"""empty message

Revision ID: 0b76f1427949
Revises: 
Create Date: 2025-04-07 15:32:11.378307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b76f1427949'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iris_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sepal_length', sa.Float(), nullable=True),
    sa.Column('sepal_width', sa.Float(), nullable=True),
    sa.Column('petal_length', sa.Float(), nullable=True),
    sa.Column('petal_width', sa.Float(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iris_predictions_id'), 'iris_predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iris_predictions_id'), table_name='iris_predictions')
    op.drop_table('iris_predictions')
    # ### end Alembic commands ###
